"""Add vehicle type, body model, transmission, and images

Revision ID: 807b6d4cc6dc
Revises: 08b80efe8ef3
Create Date: 2024-06-08 21:05:06.035865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807b6d4cc6dc'
down_revision = '08b80efe8ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicletype', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('bodymodel', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('bodymodel')
        batch_op.drop_column('vehicletype')

    # ### end Alembic commands ###
